# Generated by Django 2.2.5 on 2019-09-16 19:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numPlayers', models.IntegerField(default=0)),
                ('numPairs', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.TextField(default='', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPlayer', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findpairs.Game')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='findpairs.User')),
            ],
        ),
    ]
