# Generated by Django 2.2.5 on 2019-09-26 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findpairs', '0002_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='online',
            old_name='userName',
            new_name='user',
        ),
    ]
