# Generated by Django 2.2.5 on 2019-09-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findpairs', '0003_auto_20190926_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.TextField(default=''),
        ),
    ]
